#!/usr/bin/python
# Mail to hamcos. With customer ID and such useful stuff.
# You can specify host tags as plugin arguments. In this case the notification
# will only be executed if the host has all host tags.
# @author Robin Schneider <robin.schneider@hamcos.de>
# @company hamcos IT Service GmbH http://www.hamcos.de
# @licence AGPLv3+ <http://www.gnu.org/licenses/agpl-3.0.html>

from hamcos import *
from commonMail import *
exit_if_hosttag()

main(cust_info = True)
