#!/usr/bin/python
# SMS (using smstools)
# Notification via sms using the sms tools
# Note: You have to add the side user to the sendsms group
# and restart the site

import os
from commonSMS import *

send_sms()
